---
- name: set shit up
  hosts: hosts
  remote_user: vagrant
  become: yes

  tasks:
   - name: install git
     apt: name=git state=present
    
   - name: update repo
     apt: update_cache=yes  
   
   - name: install java
     apt: name={{item}} state=present
     with_items:
     - default-jdk
     - default-jre

   - name: install maven
     apt: name=maven state=present