---
- name: set shit up
  hosts: jusers
  remote_user: vagrant
  become: yes
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_05"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"

  tasks:
   - name: install git
     apt: name=git state=present
    
   - name: update repo
     apt: update_cache=yes  
   
   - name: Install java 8 preresequesits
     apt: name=python-software-properties

   - name: Add Java 8 repository
     apt_repository: repo='ppa:webupd8team/java'

   - name: Agree to oracle license
     debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

   - name: Install Java 8
     apt: name=oracle-java8-installer force=yes   

   - name: install maven
     apt: name=maven state=present

   - name: install wget
     apt: name=wget state=present


   - name: update again
     apt: update_cache=yes


   - name: install jenkins
     shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add - 
     shell: echo deb http://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list
    
   - name: upd8
     apt: update_cache=yes
     
   - name: install more jenkins
     shell: sudo  apt-get install  jenkins -y --force-yes 
     